ansible_network_os: nxos
cli:
  ansible_connection: network_cli
  ansible_user: loglan
  ansible_ssh_pass: vault_password
  ansible_become: yes
  ansible_become_method: enable
  ansible_become_pass: vault_enable

eapi:
  ansible_connection: httpapi
  ansible_user: loglan
  ansible_ssh_pass: vault_password
