---
- name: recup liste vlans
  nxos_facts:
    gather_subset: config
  render: config

- name: creation repertoire backup
  file:
    path: "backups/{{ inventory_hostname }}"
    state: directory
    recurse: yes

- name: sauvegarde config
  template:
    src: config.j2
    dest: "backups/{{ inventory_hostname }}/{{ inventory_hostname }}.conf

- name: create vlan "{{ idvlan }}"
  nxos_vlan:
    host: "{{ inventory_hostname }}"
    provider: "{{ cli }}"
    vlan_id: "{{ item.idvlan }}"
    name: "{{ item.namevlan }}"
    admin_state: up
    state: present
  with_items:
    - vlans
