---
- name: creer un vlan
  hosts: all

  vars_prompt:
    - name: idvlan
      prompt: "vlan ID"
      private: False
    - name: namevlan
      prompt: "vlan name"
      private: False

  tasks:
  - name: ccreation vlan "{{ idvlan }}"
    nxos-vlan:
      vlan_id: "{{ idvlan }}"
      name: "{{ namevlan }}"
      admin_state: up
      state:  present