---
- name: configure interface
  hosts: nxos
  connection: local

  vars:
    switch: 
      name: swfot1-bv12h
      intf: 
        name: Ethernet1/48
        description: Configured by Ansible

  pre_tasks:
    - debug:
        msg: "switch.name : {{ switch['name'] }}"
    - debug:
        msg: "switch['intf']['name'] : {{ switch['intf']['name'] }}"
    - debug:
        msg: "switch['intf']['description'] : {{ switch['intf']['description'] }}"
    - name: verify interface config
      nxos_command:
        host: "{{ switch['name'] }}"
        commands: "show running-config {{ switch['intf']['name'] }} | json"
        register:
          conf
    
  tasks:
    - name: create interface
      nxos_interface:
        host: "{{ switch['name'] }}"
        interface: "{{ switch['int']['name'] }}"
        description: "{{ switch['int']['description'] }}"
        mode: layer2
        admin_state: up
      changed_when: conf.description neq ''

  post_tasks:
    - name: copy run start
      nxos_command:
        host: "{{ switch['name'] }}"
        commands: "copy running-config startup-config"
