---
- name: configure vlan
  hosts: all
  connection: local

  vars_prompt:
    - name: idvlan
      prompt: "vlan ID"
      private: False
    - name: namevlan
      prompt: "vlan name"
      private: False

  tasks:
    - name: create vlan "{{ idvlan }}"
      nxos_vlan:
        host: "{{ inventory_hostname }}" 
        vlan_id: "{{ idvlan }}"
        name: "{{ namevlan }}"
        admin_state: up
        state:  present