---
- name: configure vlan
  hosts: all
  connection: local

  vars_prompt:
    - name: idvlan
      prompt: "vlan ID"
      private: False

  tasks:
    - name: remove vlan "{{ idvlan }}"
      nxos_vlan:
        host: "{{ inventory_hostname }}"
        vlan_id: "{{ idvlan }}"
        transport: nxapi
        state: absent

